server:
  port: 8081

spring:

  application:
    name: pass-batch

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/pass?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass
    password: pass
    hikari:
      maximum-pool-size: 20

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

kakaotalk:
  host: https://kapi.kakao.com
  token: TOKEN