server:
  port: 8081

spring:

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3366/oauth2?autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "xxx"
            client-secret: "xxx"
          google:
            client-id: "xxx"
            client-secret: "xxx"